// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}]
    },

    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials'}]
    },

    {
      type: 'category',
      label: 'Technical Documentation',
      items: [{type: 'autogenerated', dirName: 'technical-documentation'}]
    },
    {
      type: 'category',
      label: 'API Documentation',
      items: [{type: 'autogenerated', dirName: 'api-documentation'}]
    },
  ],
}

export default sidebars;

